os: linux
dist: xenial
language: cpp
compiler: gcc
addons:
  apt:
    packages:
      - cmake-data
      - cmake
      - ncurses-dev
script:
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build .
  - ./ncurses-example
